// Order
export const ORDER_GET_BY_ID_REQUEST = 'ORDER_GET_BY_ID_REQUEST';
export const ORDER_GET_BY_ID_SUCCESS = 'ORDER_GET_BY_ID_SUCCESS';
export const ORDER_GET_BY_ID_FAILURE = 'ORDER_GET_BY_ID_FAILURE';

export const ORDER_GET_LIST_REQUEST = 'ORDER_GET_LIST_REQUEST';
export const ORDER_GET_LIST_SUCCESS = 'ORDER_GET_LIST_SUCCESS';
export const ORDER_GET_LIST_FAILURE = 'ORDER_GET_LIST_FAILURE';

export const ORDER_CHANGE_STATUS_REQUEST = 'ORDER_CHANGE_STATUS_REQUEST';
export const ORDER_CHANGE_STATUS_SUCCESS = 'ORDER_CHANGE_STATUS_SUCCESS';
export const ORDER_CHANGE_STATUS_FAILURE = 'ORDER_CHANGE_STATUS_FAILURE';
